### ISSUE TITLE
Can't load Ska Sort

### ISSUE THREAD

**Issue by anonymous7002** [MusicTheorist/ArrayVisualizer#90] opened 2020-08-10 14:27 UTC
When I tried to build the program in Java 14 and Apache Ant 1.10.8, it worked fine, but every time I launch it, it keeps throwing this warning:
The following algorithms were not loaded due to errors: sorts.SkaSort

**Comment by landfillbaby** [comment] 2020-08-10 14:34
yeah that's a known issue. [line 59 of SkaSort.java](https://github.com/MusicTheorist/ArrayVisualizer/blob/master/src/sorts/SkaSort.java#L59) specifically disables loading it due to it being incomplete.

**Comment by landfillbaby** [comment] 2020-08-10 14:35
closing as duplicate of #52

**Comment by anonymous7002** [comment] 2020-08-10 14:36
There's a warning I have to close every time.

**Comment by landfillbaby** [comment] 2020-08-10 14:54
working on it now, i'll reopen it until then, sorry

**Comment by landfillbaby** [comment] 2020-08-11 04:00
sorry for the delay, i just pushed a commit 2ec16664ba79fc38c3c4ab51a72d39255445549 that should fix this

**Closed by landfillbaby** 2020-08-11 04:00 UTC

**Comment by anonymous7002** [comment] 2020-08-11 16:02
BUILD FAILED
build.xml:48: src doesn't support the nested "exclude" element.
